Repository kubernetes-csi/csi-driver-host-path, pull requests merged in 2019-11, with the labels that each got.

#110 Add argument for volume limits
  cmd/hostpathplugin/main.go
  pkg/hostpath/hostpath.go
  pkg/hostpath/nodeserver.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/M

#114 updated deployment: fix pod count, canary jobs
  deploy/kubernetes-1.14/canary-blacklist.txt
  deploy/kubernetes-1.15/canary-blacklist.txt
  deploy/kubernetes-1.16/canary-blacklist.txt
  deploy/util/deploy-hostpath.sh
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/M

#116 deployment: blacklist updating attacher in 1.14 to canary
  deploy/kubernetes-1.14/canary-blacklist.txt
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/XS

#115 master: update release-tools
  release-tools/build.make
  release-tools/prow.sh
  release-tools/travis.yml
  release-tools/update-vendor.sh
  release-tools/verify-go-version.sh
  release-tools/verify-vendor.sh
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XXL

#117 system pod logging
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/XS
