Repository kubernetes-csi/csi-driver-host-path, pull requests merged in 2019-03, with the labels that each got.

#14 Change example deployment scheme in multi-node cluster
  README.md
  deploy/hostpath/csi-hostpath-attacher.yaml
  deploy/hostpath/csi-hostpath-plugin.yaml
  deploy/hostpath/csi-hostpath-provisioner.yaml
  examples/csi-app.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#6 hostpath: Add block volume support
  Dockerfile
  Gopkg.lock
  deploy/hostpath/csi-hostpath-plugin.yaml
  pkg/hostpath/controllerserver.go
  pkg/hostpath/hostpath.go
  pkg/hostpath/nodeserver.go
  vendor/k8s.io/apimachinery/pkg/types/doc.go
  vendor/k8s.io/apimachinery/pkg/types/namespacedname.go
  vendor/k8s.io/apimachinery/pkg/types/nodename.go
  vendor/k8s.io/apimachinery/pkg/types/patch.go
  vendor/k8s.io/apimachinery/pkg/types/uid.go
  vendor/k8s.io/kubernetes/pkg/volume/util/volumepathhandler/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/util/volumepathhandler/volume_path_handler.go
  vendor/k8s.io/kubernetes/pkg/volume/util/volumepathhandler/volume_path_handler_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/volumepathhandler/volume_path_handler_unsupported.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#18 Add flag version
  cmd/hostpathplugin/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#19 Add snapshot to deploy example
  README.md
  deploy/deploy-hostpath.sh
  deploy/snapshotter/csi-hostpath-snpshotter.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#25 remove block file when losetup fails at volume creation
  pkg/hostpath/controllerserver.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#20 Make provisioner root persistent across reboot
  deploy/hostpath/csi-hostpath-plugin.yaml
  pkg/hostpath/controllerserver.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#26 deploy: fix PR #20
  deploy/hostpath/csi-hostpath-plugin.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#28 node: Add capability check in NodeStageVolume
  pkg/hostpath/nodeserver.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#24 embed version number
  cmd/hostpathplugin/main.go
  pkg/hostpath/hostpath.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#30 vendor check
  release-tools/build.make
  release-tools/travis.yml
  release-tools/verify-subtree.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#27 Added liveness probe to deployment example manifest
  README.md
  deploy/hostpath/csi-hostpath-plugin.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
