Repository kubernetes-csi/csi-driver-host-path, pull requests merged in 2019-04, with the labels that each got.

#29 deployment enhancements
  README.md
  deploy/deploy-hostpath.sh
  deploy/kubernetes-1.13/README.md
  deploy/kubernetes-1.13/deploy-hostpath.sh
  deploy/kubernetes-1.13/hostpath/csi-hostpath-attacher.yaml
  deploy/kubernetes-1.13/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.13/hostpath/csi-hostpath-provisioner.yaml
  deploy/kubernetes-1.13/hostpath/csi-hostpath-snapshotter.yaml
  deploy/kubernetes-1.13/hostpath/csi-hostpath-testing.yaml
  deploy/kubernetes-1.13/snapshotter/csi-hostpath-snapshotclass.yaml
  deploy/kubernetes-1.14
  deploy/kubernetes-latest
  deploy/master/README.md
  deploy/master/deploy-hostpath.sh
  deploy/master/hostpath/csi-hostpath-attacher.yaml
  deploy/master/hostpath/csi-hostpath-plugin.yaml
  deploy/master/hostpath/csi-hostpath-provisioner.yaml
  deploy/master/hostpath/csi-hostpath-snapshotter.yaml
  deploy/master/hostpath/csi-hostpath-testing.yaml
  deploy/master/snapshotter/csi-hostpath-snapshotclass.yaml
  deploy/util/deploy-hostpath.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL

#33 deploy: remove CRD installation
  deploy/util/deploy-hostpath.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#16 initial prow job
  .prow.sh
  release-tools/.prow.sh
  release-tools/README.md
  release-tools/build.make
  release-tools/filter-junit.go
  release-tools/prow.sh
  release-tools/util.sh
  release-tools/verify-shellcheck.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#35 replace '\s' to [[:space:]] for supporting macos
  deploy/util/deploy-hostpath.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#34 deploy: avoid replacing socat image
  deploy/util/deploy-hostpath.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#37 deploy: remove imagePullPolicy for livenessprobe
  deploy/kubernetes-1.13/hostpath/csi-hostpath-plugin.yaml
  deploy/master/hostpath/csi-hostpath-plugin.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#36 Prow testing: update csi-release-tools
  release-tools/build.make
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#40 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#43 deploy: intermediate update to v1.1.0-rc1
  deploy/kubernetes-1.13/hostpath/csi-hostpath-plugin.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#10 Ephemeral support
  cmd/hostpathplugin/main.go
  pkg/hostpath/controllerserver.go
  pkg/hostpath/hostpath.go
  pkg/hostpath/nodeserver.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#42 Fixed the Raw Block PV snapshot support
  deploy/kubernetes-1.13/hostpath/csi-hostpath-plugin.yaml
  deploy/master/hostpath/csi-hostpath-plugin.yaml
  examples/csi-pod-raw.yaml
  examples/csi-pvc-raw.yaml
  examples/csi-raw-pv-snapshot.yaml
  pkg/hostpath/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, sig/storage, size/M

#44 Update sidecar images to v1.1.0
  deploy/master/hostpath/csi-hostpath-attacher.yaml
  deploy/master/hostpath/csi-hostpath-plugin.yaml
  deploy/master/hostpath/csi-hostpath-provisioner.yaml
  deploy/master/hostpath/csi-hostpath-snapshotter.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/S

#45 Move snapshot example yaml files
  README.md
  examples/csi-restore.yaml
  examples/csi-snapshot.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS
