Repository kubernetes-csi/csi-driver-host-path, pull requests merged in 2019-12, with the labels that each got.

#123 Run all containers as privileged
  deploy/kubernetes-1.16/hostpath/csi-hostpath-attacher.yaml
  deploy/kubernetes-1.16/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.16/hostpath/csi-hostpath-provisioner.yaml
  deploy/kubernetes-1.16/hostpath/csi-hostpath-resizer.yaml
  deploy/kubernetes-1.16/hostpath/csi-hostpath-snapshotter.yaml
  deploy/kubernetes-1.16/hostpath/csi-hostpath-testing.yaml
Labels: approved, cncf-cla: yes, kind/flake, lgtm, release-note-none, size/M

#98 Add snapshot beta CRD deployment for 1.17
  deploy/kubernetes-1.17/README.md
  deploy/kubernetes-1.17/csi-hostpath-snapshotclass.yaml
  deploy/kubernetes-1.17/deploy-hostpath.sh
  deploy/kubernetes-1.17/hostpath/csi-hostpath-attacher.yaml
  deploy/kubernetes-1.17/hostpath/csi-hostpath-driverinfo.yaml
  deploy/kubernetes-1.17/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.17/hostpath/csi-hostpath-provisioner.yaml
  deploy/kubernetes-1.17/hostpath/csi-hostpath-resizer.yaml
  deploy/kubernetes-1.17/hostpath/csi-hostpath-snapshotter.yaml
  deploy/kubernetes-1.17/hostpath/csi-hostpath-testing.yaml
  deploy/kubernetes-1.17/snapshotter/csi-hostpath-snapshotclass.yaml
  deploy/kubernetes-latest
  deploy/util/deploy-hostpath.sh
  release-tools/build.make
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XL

#124 Run all 1.17 containers as privileged
  deploy/kubernetes-1.17/hostpath/csi-hostpath-attacher.yaml
  deploy/kubernetes-1.17/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.17/hostpath/csi-hostpath-provisioner.yaml
  deploy/kubernetes-1.17/hostpath/csi-hostpath-resizer.yaml
  deploy/kubernetes-1.17/hostpath/csi-hostpath-snapshotter.yaml
  deploy/kubernetes-1.17/hostpath/csi-hostpath-testing.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#128 deploy: fix snapshotter RBAC creation
  deploy/util/deploy-hostpath.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#126 Create snapshotclass based on snapshotter sidecar version
  deploy/util/deploy-hostpath.sh
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/S

#130 Fix errors in deploy script
  deploy/util/deploy-hostpath.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS
