Repository kubernetes-csi/csi-driver-host-path, pull requests merged in 2019-10, with the labels that each got.

#99 Use isNotMountPoint instead of isNotLikelyMountPoint
  pkg/hostpath/nodeserver.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#102 Release 1.2.0
  CHANGELOG-1.2.md
  deploy/kubernetes-1.13/README.md
  deploy/kubernetes-1.13/deploy-hostpath.sh
  deploy/kubernetes-1.13/hostpath/csi-hostpath-attacher.yaml
  deploy/kubernetes-1.13/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.13/hostpath/csi-hostpath-provisioner.yaml
  deploy/kubernetes-1.13/hostpath/csi-hostpath-resizer.yaml
  deploy/kubernetes-1.13/hostpath/csi-hostpath-snapshotter.yaml
  deploy/kubernetes-1.13/hostpath/csi-hostpath-testing.yaml
  deploy/kubernetes-1.13/snapshotter/csi-hostpath-snapshotclass.yaml
  deploy/kubernetes-1.14/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.14/hostpath/csi-hostpath-provisioner.yaml
  deploy/kubernetes-1.14/hostpath/csi-hostpath-snapshotter.yaml
  deploy/kubernetes-1.15/hostpath/csi-hostpath-attacher.yaml
  deploy/kubernetes-1.15/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.15/hostpath/csi-hostpath-provisioner.yaml
  deploy/kubernetes-1.15/hostpath/csi-hostpath-snapshotter.yaml
  deploy/kubernetes-1.16/hostpath/csi-hostpath-attacher.yaml
  deploy/kubernetes-1.16/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.16/hostpath/csi-hostpath-provisioner.yaml
  deploy/kubernetes-1.16/hostpath/csi-hostpath-resizer.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#109 deploy: share /dev with host
  deploy/kubernetes-1.14/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.15/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.16/hostpath/csi-hostpath-plugin.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S
