Repository kubernetes-csi/csi-driver-host-path, pull requests merged in 2020-07, with the labels that each got.

#190 master: update release-tools
  release-tools/cloudbuild.yaml
  release-tools/filter-junit.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#191 Update resizer version with new rbacs
  deploy/kubernetes-1.16/canary-blacklist.txt
  deploy/kubernetes-1.16/hostpath/csi-hostpath-resizer.yaml
  deploy/kubernetes-1.17/hostpath/csi-hostpath-resizer.yaml
  deploy/kubernetes-1.18/hostpath/csi-hostpath-resizer.yaml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/XS

#193 Changelog for 1.4
  CHANGELOG/CHANGELOG-1.2.md
  CHANGELOG/CHANGELOG-1.3.md
  CHANGELOG/CHANGELOG-1.4.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M
