Repository kubernetes-csi/csi-driver-host-path, pull requests merged in 2020-04, with the labels that each got.

#171 Use hostpath snapshotclass instead of pulling from snapshotter
  deploy/util/deploy-hostpath.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#172 add nodeAffinity rule to inline volume example
  examples/csi-app-inline.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/XS

#176 Remove preStop hook
  deploy/kubernetes-1.15/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.16/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.17/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.18/hostpath/csi-hostpath-plugin.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#174 Fix deploy-hostpath.sh hostpath pod and CRD conditional for k8s 1.16
  deploy/util/deploy-hostpath.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#177 Fix canary jobs
  deploy/kubernetes-1.15/README.md
  deploy/kubernetes-1.15/canary-blacklist.txt
  deploy/kubernetes-1.15/deploy-hostpath.sh
  deploy/kubernetes-1.15/deploy.sh
  deploy/kubernetes-1.15/hostpath/csi-hostpath-attacher.yaml
  deploy/kubernetes-1.15/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.15/hostpath/csi-hostpath-provisioner.yaml
  deploy/kubernetes-1.15/hostpath/csi-hostpath-resizer.yaml
  deploy/kubernetes-1.15/hostpath/csi-hostpath-snapshotter.yaml
  deploy/kubernetes-1.15/hostpath/csi-hostpath-testing.yaml
  deploy/kubernetes-1.15/snapshotter/csi-hostpath-snapshotclass.yaml
  deploy/kubernetes-1.15/test-driver.yaml
  deploy/kubernetes-1.16/canary-blacklist.txt
  deploy/kubernetes-1.17/hostpath/csi-hostpath-attacher.yaml
  deploy/kubernetes-1.18/hostpath/csi-hostpath-attacher.yaml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/L
