Repository kubernetes-csi/csi-driver-host-path, pull requests merged in 2020-01, with the labels that each got.

#134 Update sidecars with official 1.17 releases
  deploy/kubernetes-1.17/hostpath/csi-hostpath-attacher.yaml
  deploy/kubernetes-1.17/hostpath/csi-hostpath-provisioner.yaml
  deploy/kubernetes-1.17/hostpath/csi-hostpath-resizer.yaml
  deploy/kubernetes-1.17/hostpath/csi-hostpath-snapshotter.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#138 Delete unsupported 1.14 specs and deprecated connection-timeout args
  deploy/kubernetes-1.14/README.md
  deploy/kubernetes-1.14/canary-blacklist.txt
  deploy/kubernetes-1.14/deploy-hostpath.sh
  deploy/kubernetes-1.14/hostpath/csi-hostpath-attacher.yaml
  deploy/kubernetes-1.14/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.14/hostpath/csi-hostpath-provisioner.yaml
  deploy/kubernetes-1.14/hostpath/csi-hostpath-resizer.yaml
  deploy/kubernetes-1.14/hostpath/csi-hostpath-snapshotter.yaml
  deploy/kubernetes-1.14/hostpath/csi-hostpath-testing.yaml
  deploy/kubernetes-1.14/snapshotter/csi-hostpath-snapshotclass.yaml
  deploy/kubernetes-1.15/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.15/hostpath/csi-hostpath-provisioner.yaml
  deploy/kubernetes-1.15/hostpath/csi-hostpath-snapshotter.yaml
  deploy/kubernetes-1.16/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.16/hostpath/csi-hostpath-provisioner.yaml
  deploy/kubernetes-1.16/hostpath/csi-hostpath-snapshotter.yaml
  deploy/kubernetes-1.17/hostpath/csi-hostpath-plugin.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#137 Add VolumeContentSource to CreateVolumeResponse
  pkg/hostpath/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#140 Remove Brad Childs from OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS
