Repository kubernetes-csi/csi-driver-host-path, pull requests merged in 2020-03, with the labels that each got.

#162 Fixed block volume snapshots
  pkg/hostpath/controllerserver.go
  pkg/hostpath/hostpath.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#163 Remove snapshot e2e testing from alpha versions.
  deploy/kubernetes-1.15/test-driver.yaml
  deploy/kubernetes-1.16/test-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#161 Discover existing snapshots on disk
  pkg/hostpath/controllerserver.go
  pkg/hostpath/hostpath.go
  pkg/hostpath/hostpath_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/L

#166 Fix snapshot importing
  pkg/hostpath/hostpath.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/XS

#136 Remove duplicate snapshotclass file
  deploy/kubernetes-1.17/csi-hostpath-snapshotclass.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#165 Update README.md to have latest snapshot API changes
  README.md
  deploy/kubernetes-1.17/hostpath/csi-hostpath-snapshotter.yaml
  deploy/util/deploy-hostpath.sh
  docs/deploy-1.17-and-later.md
  docs/deploy-pre-1.17.md
  docs/example-ephemeral.md
  docs/example-snapshots-1.17-and-later.md
  docs/example-snapshots-pre-1.17.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XXL
