Repository kubernetes-csi/csi-driver-host-path, pull requests merged in 2021-08, with the labels that each got.

#319 master: update release-tools
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#320 Fix build on 32bit
  pkg/hostpath/controllerserver.go
Labels: kind/bug, lgtm, cncf-cla: yes, release-note, approved, size/XS, ok-to-test

#321 Clean up .travis.yml
  .travis.yml
Labels: kind/cleanup, lgtm, release-note-none, cncf-cla: yes, approved, size/XS, ok-to-test

#323 Bump livenessprobe to 2.4.0
  deploy/kubernetes-1.18-test/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.18/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.20-test/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.20/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.21-test/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.21/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-distributed/hostpath/csi-hostpath-plugin.yaml
Labels: kind/feature, size/S, lgtm, cncf-cla: yes, release-note, approved

#324 Bump 1.22 sidecar versions
  deploy/kubernetes-1.18-test/hostpath/csi-hostpath-attacher.yaml
  deploy/kubernetes-1.18-test/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.18-test/hostpath/csi-hostpath-provisioner.yaml
  deploy/kubernetes-1.18-test/hostpath/csi-hostpath-resizer.yaml
  deploy/kubernetes-1.18/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.20-test/hostpath/csi-hostpath-attacher.yaml
  deploy/kubernetes-1.20-test/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.20-test/hostpath/csi-hostpath-provisioner.yaml
  deploy/kubernetes-1.20-test/hostpath/csi-hostpath-resizer.yaml
  deploy/kubernetes-1.20-test/hostpath/csi-hostpath-snapshotter.yaml
  deploy/kubernetes-1.20/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.21-test/hostpath/csi-hostpath-attacher.yaml
  deploy/kubernetes-1.21-test/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.21-test/hostpath/csi-hostpath-provisioner.yaml
  deploy/kubernetes-1.21-test/hostpath/csi-hostpath-resizer.yaml
  deploy/kubernetes-1.21-test/hostpath/csi-hostpath-snapshotter.yaml
  deploy/kubernetes-1.21/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-distributed/hostpath/csi-hostpath-plugin.yaml
Labels: kind/cleanup, lgtm, release-note-none, cncf-cla: yes, approved, size/M

#327 Release 1.7.3 changelog
  CHANGELOG/CHANGELOG-1.7.md
Labels: kind/cleanup, lgtm, release-note-none, cncf-cla: yes, approved, size/M
