Repository kubernetes-csi/csi-driver-host-path, pull requests merged in 2022-02, with the labels that each got.

#342 Remove unused scripts in hack/ directory
  README.md
  deploy/kubernetes-1.19-test/README.md
  deploy/kubernetes-1.19-test/deploy.sh
  deploy/kubernetes-1.19-test/destroy.sh
  deploy/kubernetes-1.19-test/hostpath/csi-hostpath-attacher.yaml
  deploy/kubernetes-1.19-test/hostpath/csi-hostpath-driverinfo.yaml
  deploy/kubernetes-1.19-test/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.19-test/hostpath/csi-hostpath-provisioner.yaml
  deploy/kubernetes-1.19-test/hostpath/csi-hostpath-resizer.yaml
  deploy/kubernetes-1.19-test/hostpath/csi-hostpath-snapshotclass.yaml
  deploy/kubernetes-1.19-test/hostpath/csi-hostpath-snapshotter.yaml
  deploy/kubernetes-1.19-test/hostpath/csi-hostpath-testing.yaml
  deploy/kubernetes-1.19-test/test-driver.yaml
  deploy/kubernetes-1.19/README.md
  deploy/kubernetes-1.19/deploy.sh
  deploy/kubernetes-1.19/destroy.sh
  deploy/kubernetes-1.19/hostpath/csi-hostpath-driverinfo.yaml
  deploy/kubernetes-1.19/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.19/hostpath/csi-hostpath-snapshotclass.yaml
  deploy/kubernetes-1.19/hostpath/csi-hostpath-testing.yaml
  deploy/kubernetes-1.19/test-driver.yaml
  deploy/kubernetes-1.20-test/README.md
  deploy/kubernetes-1.20-test/deploy.sh
  deploy/kubernetes-1.20-test/destroy.sh
  deploy/kubernetes-1.20-test/hostpath/csi-hostpath-attacher.yaml
  deploy/kubernetes-1.20-test/hostpath/csi-hostpath-driverinfo.yaml
  deploy/kubernetes-1.20-test/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.20-test/hostpath/csi-hostpath-provisioner.yaml
  deploy/kubernetes-1.20-test/hostpath/csi-hostpath-resizer.yaml
  deploy/kubernetes-1.20-test/hostpath/csi-hostpath-snapshotclass.yaml
  deploy/kubernetes-1.20-test/hostpath/csi-hostpath-snapshotter.yaml
  deploy/kubernetes-1.20-test/hostpath/csi-hostpath-testing.yaml
  deploy/kubernetes-1.20-test/test-driver.yaml
  deploy/kubernetes-1.20/README.md
  deploy/kubernetes-1.20/deploy.sh
  deploy/kubernetes-1.20/destroy.sh
  deploy/kubernetes-1.20/hostpath/csi-hostpath-driverinfo.yaml
  deploy/kubernetes-1.20/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.20/hostpath/csi-hostpath-snapshotclass.yaml
  deploy/kubernetes-1.20/hostpath/csi-hostpath-testing.yaml
  deploy/kubernetes-1.20/test-driver.yaml
  deploy/kubernetes-1.21-test/hostpath/csi-hostpath-attacher.yaml
  deploy/kubernetes-1.21-test/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.21-test/hostpath/csi-hostpath-provisioner.yaml
  deploy/kubernetes-1.21-test/hostpath/csi-hostpath-resizer.yaml
  deploy/kubernetes-1.21/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-distributed/hostpath/csi-hostpath-plugin.yaml
  docs/deploy-pre-1.17.md
  docs/example-snapshots-pre-1.17.md
  hack/e2e-hostpath.sh
  hack/get-sanity.sh
Labels: kind/cleanup, lgtm, release-note-none, cncf-cla: yes, approved, size/XXL

#346 Update csi-snapshotter images to v5.0.1
  deploy/kubernetes-1.21-test/hostpath/csi-hostpath-snapshotter.yaml
  deploy/kubernetes-1.21/hostpath/csi-hostpath-plugin.yaml
Labels: kind/cleanup, lgtm, release-note-none, cncf-cla: yes, approved, size/XS

#339 ControllerGetVolume should report abnormal volume condition if volume…
  pkg/hostpath/controllerserver.go
Labels: kind/bug, size/S, lgtm, cncf-cla: yes, release-note, approved
