Repository kubernetes-csi/csi-driver-host-path, pull requests merged in 2023-12, with the labels that each got.

#480 fix missing published target paths when republish the ephemeral volume
  pkg/hostpath/nodeserver.go
Labels: kind/bug, size/S, lgtm, cncf-cla: yes, release-note, approved

#483 Cherry pick of #480: fix missing published target paths when republish the ephemeral volume
  pkg/hostpath/nodeserver.go
Labels: size/S, lgtm, cncf-cla: yes, release-note, approved

#484 Update release tools to fix broken image build pipeline
  release-tools/KUBERNETES_CSI_OWNERS_ALIASES
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/go-modules-update.sh
  release-tools/prow.sh
Labels: lgtm, size/L, release-note-none, cncf-cla: yes, approved

#487 Update dependency go modules for k8s v1.29.0
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/modules.txt
Labels: lgtm, size/L, cncf-cla: yes, release-note, approved

#485 Changelog for v1.12.1
  CHANGELOG/CHANGELOG-1.12.md
Labels: size/S, lgtm, release-note-none, cncf-cla: yes, approved

#489 bump image versions
  deploy/kubernetes-1.26-test/hostpath/csi-hostpath-attacher.yaml
  deploy/kubernetes-1.26-test/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.26-test/hostpath/csi-hostpath-provisioner.yaml
  deploy/kubernetes-1.26-test/hostpath/csi-hostpath-resizer.yaml
  deploy/kubernetes-1.26-test/hostpath/csi-hostpath-snapshotter.yaml
  deploy/kubernetes-1.26/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-distributed/hostpath/csi-hostpath-plugin.yaml
  hack/bump-image-versions.sh
Labels: kind/cleanup, lgtm, release-note-none, cncf-cla: yes, approved, size/M

#481 hostpath driver implements the ControllerModityVolume feature
  cmd/hostpathplugin/main.go
  pkg/hostpath/controllerserver.go
  pkg/hostpath/controllerserver_test.go
  pkg/hostpath/flag.go
  pkg/hostpath/hostpath.go
Labels: kind/feature, lgtm, size/L, cncf-cla: yes, release-note, approved
