Repository kubernetes-csi/csi-driver-host-path, pull requests merged in 2023-10, with the labels that each got.

#458 Fix state file update after stage/publish action
  pkg/state/state.go
Labels: kind/bug, lgtm, release-note-none, cncf-cla: yes, approved, size/XS

#464 Add replace for k8s.io/endpointslice
  go.mod
  vendor/modules.txt
Labels: kind/cleanup, lgtm, release-note-none, cncf-cla: yes, approved, size/XS

#465 Add changelog for 1.12
  CHANGELOG/CHANGELOG-1.12.md
Labels: lgtm, size/L, release-note-none, kind/documentation, cncf-cla: yes, approved
