Repository kubernetes-csi/csi-driver-host-path, pull requests merged in 2024-06, with the labels that each got.

#528 bump image versions
  deploy/kubernetes-1.27-test/hostpath/csi-hostpath-attacher.yaml
  deploy/kubernetes-1.27-test/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.27-test/hostpath/csi-hostpath-provisioner.yaml
  deploy/kubernetes-1.27-test/hostpath/csi-hostpath-resizer.yaml
  deploy/kubernetes-1.27-test/hostpath/csi-hostpath-snapshotter.yaml
  deploy/kubernetes-1.27/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-distributed/hostpath/csi-hostpath-plugin.yaml
Labels: kind/feature, size/S, lgtm, cncf-cla: yes, release-note, approved

#531 correct the file name of groupvolumesnapshot
  examples/csi-groupsnapshot-v1alpha1.yaml
Labels: lgtm, release-note-none, cncf-cla: yes, approved, size/XS, ok-to-test

#532 Update images to latest patch releases
  deploy/kubernetes-1.27-test/hostpath/csi-hostpath-attacher.yaml
  deploy/kubernetes-1.27-test/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.27-test/hostpath/csi-hostpath-provisioner.yaml
  deploy/kubernetes-1.27-test/hostpath/csi-hostpath-resizer.yaml
  deploy/kubernetes-1.27-test/hostpath/csi-hostpath-snapshotter.yaml
  deploy/kubernetes-1.27/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-distributed/hostpath/csi-hostpath-plugin.yaml
Labels: kind/cleanup, size/S, lgtm, release-note-none, cncf-cla: yes, approved

#534 switch from glog to klog
  cmd/hostpathplugin/main.go
  go.mod
  go.sum
  internal/proxy/proxy.go
  pkg/hostpath/controllerserver.go
  pkg/hostpath/groupcontrollerserver.go
  pkg/hostpath/healthcheck.go
  pkg/hostpath/hostpath.go
  pkg/hostpath/identityserver.go
  pkg/hostpath/nodeserver.go
  pkg/hostpath/server.go
  vendor/github.com/golang/glog/LICENSE
  vendor/github.com/golang/glog/README.md
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/github.com/golang/glog/glog_file_linux.go
  vendor/github.com/golang/glog/glog_file_other.go
  vendor/github.com/golang/glog/glog_file_posix.go
  vendor/github.com/golang/glog/glog_flags.go
  vendor/github.com/golang/glog/internal/logsink/logsink.go
  vendor/github.com/golang/glog/internal/logsink/logsink_fatal.go
  vendor/github.com/golang/glog/internal/stackdump/stackdump.go
  vendor/modules.txt
Labels: kind/cleanup, lgtm, cncf-cla: yes, release-note, approved, size/XXL, ok-to-test

#535 Add changelog for v1.14.0
  CHANGELOG/CHANGELOG-1.14.md
Labels: lgtm, release-note-none, kind/documentation, cncf-cla: yes, approved, size/M

#536 bump hostpath image to 1.14.0
  deploy/kubernetes-1.27-test/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.27-test/hostpath/csi-hostpath-testing.yaml
  deploy/kubernetes-1.27/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.27/hostpath/csi-hostpath-testing.yaml
  deploy/kubernetes-distributed/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-distributed/hostpath/csi-hostpath-testing.yaml
Labels: kind/feature, size/S, lgtm, release-note-none, cncf-cla: yes, approved

#537 bump hostpath image to 1.14.0
  deploy/kubernetes-1.27-test/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.27-test/hostpath/csi-hostpath-testing.yaml
  deploy/kubernetes-1.27/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.27/hostpath/csi-hostpath-testing.yaml
  deploy/kubernetes-distributed/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-distributed/hostpath/csi-hostpath-testing.yaml
Labels: kind/feature, size/S, lgtm, cncf-cla: yes, release-note, approved
