Repository kubernetes-csi/csi-driver-host-path, pull requests merged in 2025-06, with the labels that each got.

#597 Add --enable-list-snapshots command-line option
  cmd/hostpathplugin/main.go
  pkg/hostpath/controllerserver.go
  pkg/hostpath/hostpath.go
Labels: kind/feature, lgtm, cncf-cla: yes, release-note, approved, size/XS

#605 Add `-automaxprocs` flag for configuring `GOMAXPROCS`
  cmd/hostpathplugin/main.go
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/protosanitizer.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/standardflags/automaxprocs.go
  vendor/go.uber.org/automaxprocs/LICENSE
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroup.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroups.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroups2.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/doc.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/errors.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/mountpoint.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/subsys.go
  vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_linux.go
  vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_unsupported.go
  vendor/go.uber.org/automaxprocs/internal/runtime/runtime.go
  vendor/go.uber.org/automaxprocs/maxprocs/maxprocs.go
  vendor/go.uber.org/automaxprocs/maxprocs/version.go
  vendor/modules.txt
Labels: kind/feature, lgtm, cncf-cla: yes, release-note, approved, size/XXL

#595 Updated external-snapshot-metadata sidecar support to its alpha level
  deploy/kubernetes-1.30/hostpath/csi-snapshot-metadata-sidecar.patch
  docs/example-snapshot-metadata.md
Labels: kind/feature, lgtm, size/L, cncf-cla: yes, release-note, approved
