Repository kubernetes-csi/csi-driver-host-path, pull requests merged in 2025-03, with the labels that each got.

#579 fix: consider only non-zero blocks for GetMetadataAllocated
  pkg/hostpath/snapshotmetadata.go
Labels: kind/bug, size/S, lgtm, cncf-cla: yes, release-note, approved, ok-to-test

#587 Implement dynamic `MaxVolumesPerNode`
  pkg/hostpath/nodeserver.go
Labels: kind/feature, lgtm, cncf-cla: yes, release-note, approved, size/XS

#577 Tighter checks on CreateVolume CapacityRange
  pkg/hostpath/controllerserver.go
Labels: size/S, lgtm, release-note-none, cncf-cla: yes, approved, ok-to-test

#586 Use GNU tar in the Docker image
  Dockerfile
Labels: kind/bug, lgtm, cncf-cla: yes, release-note, approved, size/XS

#590 Use GNU tar in the Docker image
  Dockerfile
Labels: kind/bug, lgtm, cncf-cla: yes, release-note, approved, size/XS

#592 Add changelog for v1.16.1
  CHANGELOG/CHANGELOG-1.16.md
Labels: size/S, lgtm, release-note-none, kind/documentation, cncf-cla: yes, approved
