Repository kubernetes-csi/csi-driver-host-path, pull requests merged in 2025-02, with the labels that each got.

#582 nominate myself as an approver
  OWNERS
Labels: lgtm, release-note-none, kind/documentation, cncf-cla: yes, approved, size/XS

#581 Update deployment structure and sidecar versions for Kubernetes 1.32
  .prow.sh
  deploy/kubernetes-1.28
  deploy/kubernetes-1.28-test
  deploy/kubernetes-1.30-test/README.md
  deploy/kubernetes-1.30-test/deploy.sh
  deploy/kubernetes-1.30-test/destroy.sh
  deploy/kubernetes-1.30-test/hostpath/csi-hostpath-attacher.yaml
  deploy/kubernetes-1.30-test/hostpath/csi-hostpath-driverinfo.yaml
  deploy/kubernetes-1.30-test/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.30-test/hostpath/csi-hostpath-provisioner.yaml
  deploy/kubernetes-1.30-test/hostpath/csi-hostpath-resizer.yaml
  deploy/kubernetes-1.30-test/hostpath/csi-hostpath-snapshotclass.yaml
  deploy/kubernetes-1.30-test/hostpath/csi-hostpath-snapshotter.yaml
  deploy/kubernetes-1.30-test/hostpath/csi-hostpath-testing.yaml
  deploy/kubernetes-1.30-test/test-driver.yaml
  deploy/kubernetes-1.30/README.md
  deploy/kubernetes-1.30/deploy.sh
  deploy/kubernetes-1.30/destroy.sh
  deploy/kubernetes-1.30/hostpath/csi-hostpath-driverinfo.yaml
  deploy/kubernetes-1.30/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-1.30/hostpath/csi-hostpath-snapshotclass.yaml
  deploy/kubernetes-1.30/hostpath/csi-hostpath-testing.yaml
  deploy/kubernetes-1.30/hostpath/csi-snapshot-metadata-sidecar.patch
  deploy/kubernetes-1.30/test-driver.yaml
  deploy/kubernetes-1.31
  deploy/kubernetes-1.31-test
  deploy/kubernetes-distributed/hostpath/csi-hostpath-plugin.yaml
  deploy/kubernetes-latest
  deploy/kubernetes-latest-test
Labels: kind/cleanup, lgtm, cncf-cla: yes, release-note, approved, size/M

#583 Explicit replace directives for Kubernetes dependencies
  go.mod
  vendor/modules.txt
Labels: kind/cleanup, lgtm, size/L, release-note-none, cncf-cla: yes, approved

#584 Add changelog for v1.16.0
  CHANGELOG/CHANGELOG-1.16.md
Labels: lgtm, size/L, release-note-none, kind/documentation, cncf-cla: yes, approved
